### ISSUE TITLE
Take the Number of Hearbeats instead the icon 

### ISSUE THREAD

**Issue by dasgamingsofa** [bfroggio/heart-of-frogg#10]
Hey :) Found your way to show the heartrate on a Twitch-Stream. 
At this point: Thank you very much! Really.

But one issue: On the last line you write, that is easy to switch the heart-icon with the really number of hearbeats - but not how. I looked in the index, but I dont know how to switch it. Can you explain it please?

Greets,
Alex
(from Germany, sorry for bad english)

**Comment by jessemillar** [comment]
Hey, Alex! Sorry I missed this. I actually just added this functionality so nothing new needs to be added anymore. Just use the latest ui/index.html file and it'll show your heartrate as a number and an icon (you can edit it to show only the icon or only the number too).
