### ISSUE TITLE
Help please :)

### ISSUE THREAD

**Issue by ZohZie** [bfroggio/heart-of-frogg#11]
i'm not sure what is going on, of if this is normal, but when starting the server exe i get "⇨ http server started on [::]:8080" 
should there be an ip address in the [::] box? [https://prnt.sc/5AWqlX0OIQib](url)
I tried my default one listed "192.168.1.101" in the apps settings. But nothing is showing other than a 0 on the site. [https://prnt.sc/CR-aBdIxIK4W](url)
The watch app is reading the bpm correctly.  i tried opening my ports for 8080 in my isp settings page too, but nothing changed.

**Comment by jessemillar** [comment]
Sorry for the delay! I didn't get notified you opened an issue. The server is supposed to show your IP address when you start it but it's not a foolproof method. You can manually find your IP address [like this](https://support.microsoft.com/en-us/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9).

**Comment by jessemillar** [comment]
Gonna close this due to inactivity and I'm hopeful my response solves the problem. Feel free to reopen if you have more issues.
