### ISSUE TITLE
OBS Display font size and style is not the same as the heart

### ISSUE THREAD

**Issue by NavekFPS** [bfroggio/heart-of-frogg#12]
Hi! It works very good :) the only thing is that the display on obs is bugged out, the font size and style is not the same! Let me know if you can help!

![Screenshot 2022-08-08 113325](https://user-images.githubusercontent.com/110836714/183442951-e1e27ab0-1051-442b-b2bc-65d055017c9c.png)

**Comment by zachpcmr** [comment]
Hey I found a fix for this if you are still interested!
-HOW TO FIX FORMAT ISSUE-
YOU HAVE TO HAVE A COMPILER
I use visual studios.
 
1. go into your files for heart of frog,
2. go into your ui
3. drag the index.html file into visual studios
4. paste this fixed version




[fix.txt](https://github.com/bfroggio/heart-of-frogg/files/9391228/fix.txt)

5. save the file, and then refresh scene in obs

let it be known I only code in c++ so this is a spaghetti fix at best. It works tho!
if anyone needs help, my discord is Rãt King#7102

**Comment by jessemillar** [comment]
Thanks for the fix! Looks like someone else made a PR with it which I just merged in. I'll rebuild it soon and post the new version to the Fitbit store.

**Comment by jessemillar** [comment]
I'm silly. The UI issue reported in this thread didn't actually need a rebuild of the watch app. Either way, the fix is merged. You can just follow the instructions in the README file again and you'll get the latest version.
