### ISSUE TITLE
Problems with installing

### ISSUE THREAD

**Issue by RealDennome** [bfroggio/heart-of-frogg#15]
Bought a brand new Versa 2 (to set up the Heartrate in OBS) but if I open the app per link in Readme I can't install it :(

Shows Heart of Frogg in the Fitbit App but "install" is just grey - like its not compatible

Do you could know why?

**Comment by jessemillar** [comment]
That's odd. Lemme dig out my old Versa and see if I can get it to work again.

**Comment by jessemillar** [comment]
@RealDennome I just rebuilt the app and re-uploaded it to the Fitbit App Store. I also added a screenshot for good measure in case that was somehow blocking downloads. Could you try installing again? And if you have issues, which OS version do you have on your Versa?

**Comment by RealDennome** [comment]
Hey there!

Got Firmware Vers.: 35.70.7.14

Using a Samsung Galaxy S22 as app holder :)


I tried it again but it won't work :/ Still no possiblity to download

**Comment by jessemillar** [comment]
I just dug my old Versa 2 out of a drawer and re-paired it with my phone. I'm using an iPhone which might make a difference but shouldn't. When I went to the app link, the install button was initially grayed out but when I tapped it it gave me a warning about it being a "private app" (expected) and then turned the button green. Just noticed my Versa 2 is on firmware version 35.72.1.9 though which is a bit ahead of yours. Can you try updating and see if that allows the download?
![image](https://user-images.githubusercontent.com/4627837/191536286-6dbaec18-e5f2-47c8-b4af-bab86d9a060d.png)

**Comment by RealDennome** [comment]
Hey bud! Sorry for the late Response. It has to be a Problem with Android which i'll try to solve tomorrow to set up the watch with a cable on my PC and hopefully the Firmware Update

**Comment by RealDennome** [comment]
I tried all. Connecting with my Laptop (for bluetooth) and no update still. Is your app maybe just functionally on iOS because there is a higher firmware?

Very annoying for me :(

**Comment by jessemillar** [comment]
Weird... Out of curiosity, have you tried both store links in the README? I wonder if the code I have uploaded just isn't compatible with your device for some reason? It's annoying there's no error message on the store page saying WHY you can't install since that would really help with the debugging process.

**Comment by RealDennome** [comment]
Got the Update today! Installation possible :)
