### ISSUE TITLE
Cant find in app store

### ISSUE THREAD

**Issue by skellingtondragon** [bfroggio/heart-of-frogg#17]
My friend just sent this to me because I was looking for a way to be able to show my heart rate on stream without having to get a pulsoid.  I am getting zero search results in the fitbit app store for Heart of Frogg, so I don't know how to go about getting this to work.  I have a Versa lite.

**Comment by jessemillar** [comment]
Check the README file. There's instructions and links.

**Comment by skellingtondragon** [comment]
I was following that, but it takes me to a webpage and tells me to find it in the fitbit app on my device, which I can't do.  There isn't a way to install it from my PC.

**Comment by jessemillar** [comment]
There's a link to two versions of the app. Gotta click one of those depending on your device. Go to the link on your phone.

**Comment by skellingtondragon** [comment]
Ah ok!  I didn't realize it needed to be done via phone to get it to work.  Sometimes my brain doesn't fully work.  :)

**Comment by jessemillar** [comment]
Nah. That's less a "you" problem and more an issue with my documentation. Docs are supposed to be clear! Apologies for closing this issue without considering there was room for improvement on my part. I updated the README just now to mention the need to open the link on your phone.
