### ISSUE TITLE
Doesnt work with fitbit Sense 

### ISSUE THREAD

**Issue by DragoniaGaming** [bfroggio/heart-of-frogg#19]
I followed All the steps you described, But it still doesnt work in OBS.

the Connection from the Watch to the all Seems Fine and i added the right Browser source to obs. 

But it still doesnt work.

**Comment by jessemillar** [comment]
When you open the `/ui/index.html` directly in a web browser, does the heart animation show and is the heart rate something greater than 0?

**Comment by DragoniaGaming** [comment]
Yeah That World fine.

**Comment by DragoniaGaming** [comment]
That works*

**Comment by jessemillar** [comment]
Could you share a screenshot of how you have the browser source configured in OBS?

**Comment by DragoniaGaming** [comment]
I am confused. Now it Works also Perfect in obs. But a few hours Ago nothing worked, no matter what i tried. 

Thank you for your help. I will definetly come back, if i have any issues again.

Also grait praise to your work! You are the only one who have an Solution for connecting obs with fitbit.

**Comment by jessemillar** [comment]
Glad it works now! Hope it improves your streams.
