### ISSUE TITLE
I am looking forward to using it with OBS.

### ISSUE THREAD

**Issue by hulwarilin** [bfroggio/heart-of-frogg#21]
I couldn't get my heart rate so I'll share.
It's a great app and I really appreciate it.

Watch model…Versa2
Firmware version number…35.72.1.23
The type of phone … Android 12
Fitbit app version number…3.72.fitbit-mobile-37268001-489675908

**Comment by jessemillar** [comment]
Did you follow the [troubleshooting steps](https://github.com/bfroggio/heart-of-frogg#troubleshooting)? Do you get an error anywhere? I need more info to help you debug.

**Comment by hulwarilin** [comment]
I followed the troubleshooting steps. Heart rate data cannot be acquired and remains 0.

**Comment by jessemillar** [comment]
Darn. I was hoping you hadn't followed the troubleshooting steps yet. If you've already gone through those, there's likely a configuration issue with either your firewall or your router and I'm not knowledgeable enough to help with either of those...
